export const ACTIONS_DATA = {
  SET_PROJECTS: "SET_PROJECTS",
  SET_PROJECT: "SET_PROJECT",
  CHANGE_PROJECT: "CHANGE_PROJECT",
  ADD_PROJECT: "ADD_PROJECT",
  REMOVE_PROJECT: "REMOVE_PROJECT",
  TOGGLE_PROJECTS_LOADING: "TOGGLE_PROJECTS_LOADING",
  TOGGLE_PROJECT_LOADING: "TOGGLE_PROJECT_LOADING",
  TOGGLE_PROJECT_MODAL: "TOGGLE_PROJECT_MODAL",
}